Fixed error causing failed startup
Error was:
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.isJsonObject()" because "element" is null
 at net.pms.util.APIUtils.setApiImageBaseURL(APIUtils.java:232)
 at net.pms.PMS.init(PMS.java:631)
 at net.pms.PMS.createInstance(PMS.java:867)
 at net.pms.PMS.main(PMS.java:1021)